#version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.0
    container_name: terraform-localstack
    ports:
      - "4566:4566"            # LocalStack endpoint
      - "4510-4559:4510-4559"  # External services port range
    environment:
      # Servicios AWS a emular
      - SERVICES=s3,ec2,iam,lambda,cloudformation,logs,events
      # Configuración
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp}/localstack
      # Persistencia de datos
      - PERSISTENCE=1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - terraform-network

networks:
  terraform-network:
    driver: bridge